// ============================================================
// PRODUCT DATA – SMRITA
// ============================================================
// HOW TO REPLACE IMAGES:
// 1. Place your product images in /public/images/products/
// 2. Replace the image URLs below with: /images/products/your-image.jpg
// 3. The placeholder field is used when no image is available
// ============================================================

export const PRODUCTS = [
  {
    id: 1,
    name: "Chandan",
    subtitle: "Sacred Sandalwood",
    description:
      "Crafted from premium & natural ingredients, our Chandan incense sticks are 100% charcoal free and hand-crafted with devotion. Less smoke helps uplift the mind & spirit.",
    longDescription:
      "Made of Cow-Dung, Chandan (Sandalwood Powder), Wood Powder, Essential Oils (Natural Fragrance Oils). Long lasting premium fragrance with premium essential oils for best fragrances. Each stick burns for 30–35 minutes. Comes in a Refill & Reuse Jar with 3-inch longer sticks.",
    price: 100,
    mrp: 120,
    image: "/images/products/c.jpeg",
    category: "Sandalwood",
    scent: "Woody, Warm, Sacred",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    quantity: 50,
    sticksPerPack: 50,
    tags: ["bestseller", "meditation"],
    rating: 4.9,
    reviews: 128,
    inStock: true,
    featured: true,
    color: "#8B6914",
    ingredients: "Cow-Dung, Chandan (Sandalwood Powder), Wood Powder, Essential Oils (Natural Fragrance Oils)",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
    features: [
      "Long lasting premium fragrance",
      "Made of premium & natural ingredients",
      "Hand-crafted with Devotion",
      "Less smoke helps uplift the mind & spirit",
      "100% charcoal free",
      "Premium essential oils for best fragrances",
      "Refill & Reuse Jar",
      "3 inches longer sticks",
    ],
  },
  {
    id: 2,
    name: "Gulab",
    subtitle: "Rose of the Divine",
    description:
      "Crafted from premium & natural ingredients, our Gulab (Rose) incense sticks are 100% charcoal free and hand-crafted with devotion. Less smoke helps uplift the mind & spirit.",
    longDescription:
      "Made of Cow-Dung, Rose (waste rose petals Powder), Wood Powder, Essential Oils (Natural Fragrance Oils). Long lasting premium fragrance with premium essential oils for best fragrances. Each stick burns for 30–35 minutes. Comes in a Refill & Reuse Jar with 3-inch longer sticks.",
    price: 100,
    mrp: 120,
    image: "/images/products/r.jpeg",
    category: "Floral",
    scent: "Sweet, Floral, Romantic",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    quantity: 50,
    sticksPerPack: 50,
    tags: ["popular", "floral"],
    rating: 4.8,
    reviews: 95,
    inStock: true,
    featured: true,
    color: "#9B2335",
    ingredients: "Cow-Dung, Rose (waste rose petals Powder), Wood Powder, Essential Oils (Natural Fragrance Oils)",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
    features: [
      "Long lasting premium fragrance",
      "Made of premium & natural ingredients",
      "Hand-crafted with Devotion",
      "Less smoke helps uplift the mind & spirit",
      "100% charcoal free",
      "Premium essential oils for best fragrances",
      "Refill & Reuse Jar",
      "3 inches longer sticks",
    ],
  },
  {
    id: 3,
    name: "Lavender",
    subtitle: "Lavender Bliss",
    description:
      "Crafted from premium & natural ingredients, our Lavender incense sticks are 100% charcoal free and hand-crafted with devotion. Less smoke helps uplift the mind & spirit.",
    longDescription:
      "Made of Cow-Dung, flower waste (lavender flower petals Powder), Wood Powder, Essential Oils (Natural Fragrance Oils). Long lasting premium fragrance with premium essential oils for best fragrances. Each stick burns for 30–35 minutes. Comes in a Refill & Reuse Jar with 3-inch longer sticks.",
    price: 100,
    mrp: 120,
    image: "/images/products/l.jpeg",
    category: "Floral",
    scent: "Floral, Fresh, Calming",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    quantity: 50,
    sticksPerPack: 50,
    tags: ["classic", "calming"],
    rating: 5.0,
    reviews: 212,
    inStock: true,
    featured: true,
    color: "#4A235A",
    ingredients: "Cow-Dung, flower waste (lavender flower petals Powder), Wood Powder, Essential Oils (Natural Fragrance Oils)",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
    features: [
      "Long lasting premium fragrance",
      "Made of premium & natural ingredients",
      "Hand-crafted with Devotion",
      "Less smoke helps uplift the mind & spirit",
      "100% charcoal free",
      "Premium essential oils for best fragrances",
      "Refill & Reuse Jar",
      "3 inches longer sticks",
    ],
  },
  {
    id: 4,
    name: "Mogra",
    subtitle: "Arabian Jasmine",
    description:
      "Crafted from premium & natural ingredients, our Mogra (Jasmine) incense sticks are 100% charcoal free and hand-crafted with devotion. Less smoke helps uplift the mind & spirit.",
    longDescription:
      "Made of Cow-Dung, Arabian Jasmine (Mogra petals Powder), Wood Powder, Essential Oils (Natural Fragrance Oils). Long lasting premium fragrance with premium essential oils for best fragrances. Each stick burns for 30–35 minutes. Comes in a Refill & Reuse Jar with 3-inch longer sticks.",
    price: 100,
    mrp: 120,
    image: "/images/products/m.jpeg",
    category: "Floral",
    scent: "Jasmine, Sweet, Intoxicating",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    quantity: 50,
    sticksPerPack: 50,
    tags: ["floral", "goddess"],
    rating: 4.9,
    reviews: 67,
    inStock: true,
    featured: false,
    color: "#2D6A2F",
    ingredients: "Cow-Dung, Arabian Jasmine (Mogra petals Powder), Wood Powder, Essential Oils (Natural Fragrance Oils)",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
    features: [
      "Long lasting premium fragrance",
      "Made of premium & natural ingredients",
      "Hand-crafted with Devotion",
      "Less smoke helps uplift the mind & spirit",
      "100% charcoal free",
      "Premium essential oils for best fragrances",
      "Refill & Reuse Jar",
      "3 inches longer sticks",
    ],
  },
  // ============================================================
  // BAAKI PRODUCTS (id 5–9) ke liye PDF data abhi available
  // nahi hai — placeholder rakha hai, update kar sakte ho
  // ============================================================
  {
    id: 5,
    name: "Tulsi Dhoop",
    subtitle: "Holy Basil Purifier",
    description: "Grown in sacred soil, Tulsi is the most revered plant in Hinduism. These sticks purify the air and the soul simultaneously.",
    longDescription:
      "Tulsi (Holy Basil) is considered the most sacred plant in Hindu tradition, associated with Vishnu and used in every major ritual. Our Tulsi Dhoop uses leaves harvested from plants grown in temple gardens in Vrindavan. The crisp, slightly peppery green scent is known for its antibacterial properties and its ability to clear negative energy from living spaces.",
    price: 100,
    mrp: 120,
    image: "https://images.unsplash.com/photo-1536147116438-62679a5e01f2?w=600&q=80",
    category: "Herbal",
    scent: "Fresh, Green, Purifying",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    quantity: 50,
    sticksPerPack: 50,
    tags: ["herbal", "purifying"],
    rating: 4.7,
    reviews: 88,
    inStock: true,
    featured: false,
    color: "#2D6A4F",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
  },
  {
    id: 6,
    name: "Loban Resin",
    subtitle: "Ancient Frankincense",
    description: "Pure Loban resin sticks — the same incense that has been burned in mosques, temples, and churches across the ancient world for millennia.",
    longDescription:
      "Loban (Benzoin/Frankincense resin) is one of humanity's oldest sacred substances, traded along the ancient Silk Road and burned in every major religious tradition on Earth. Our sticks use 100% pure Loban resin without any fillers.",
    price: 100,
    mrp: 120,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80",
    category: "Resin",
    scent: "Deep, Balsamic, Ancient",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    quantity: 50,
    sticksPerPack: 50,
    tags: ["ancient", "meditation"],
    rating: 4.8,
    reviews: 74,
    inStock: true,
    featured: false,
    color: "#6B4423",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
  },
  {
    id: 7,
    name: "Mogra Bela",
    subtitle: "Jasmine Moonlight",
    description: "The intoxicating scent of Mogra jasmine flowers, harvested under moonlight when their fragrance blooms most intensely.",
    longDescription:
      "Mogra (Arabian Jasmine) is the queen of night-blooming flowers, and our Mogra Bela captures her at her most potent. This delicate, intensely floral incense is traditionally offered to goddesses and is said to attract love, abundance, and spiritual blessings into the home.",
    price: 100,
    mrp: 120,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    category: "Floral",
    scent: "Jasmine, Sweet, Intoxicating",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    quantity: 50,
    sticksPerPack: 50,
    tags: ["floral", "goddess"],
    rating: 4.8,
    reviews: 103,
    inStock: true,
    featured: false,
    color: "#F0EAD6",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
  },
  {
    id: 8,
    name: "Havan Samagri",
    subtitle: "Sacred Fire Blend",
    description: "A sacred blend of 21 herbs and resins traditionally used in Vedic fire ceremonies. Adapted into incense sticks for daily rituals.",
    longDescription:
      "Our Havan Samagri stick is based on an ancient recipe that includes camphor, guggul, agar wood, clove, cardamom, and 16 other sacred herbs and resins. This powerful blend is traditionally burned during Vedic havan ceremonies to purify the environment and create a bridge between the earthly and divine realms.",
    price: 100,
    mrp: 120,
    image: "https://images.unsplash.com/photo-1543362906-acfc16c67564?w=600&q=80",
    category: "Vedic",
    scent: "Camphor, Herbal, Sacred",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    quantity: 50,
    sticksPerPack: 50,
    tags: ["vedic", "ceremony"],
    rating: 4.9,
    reviews: 156,
    inStock: true,
    featured: false,
    color: "#D4860A",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
  },
  {
    id: 9,
    name: "Oud Majlis",
    subtitle: "Arabian Oud Wood",
    description: "The rarest wood in the world — Oud (Agarwood) — from the forests of Assam. One of the most prized fragrances in human history.",
    longDescription:
      "Oud (Agarwood) is the resinous heartwood of the Aquilaria tree, formed only when the tree responds to fungal infection — a process that takes decades. Our Oud Majlis uses genuine Assamese agarwood chips blended into our handmade sticks.",
    price: 100,
    mrp: 120,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    category: "Luxury",
    scent: "Smoky, Complex, Deep",
    burnTime: "30–35 mins per stick",
    netWeight: "100g",
    quantity: 50,
    sticksPerPack: 50,
    tags: ["luxury", "oud", "rare"],
    rating: 5.0,
    reviews: 45,
    inStock: true,
    featured: false,
    color: "#2C1810",
    manufacturer: "SMRITA Enterprises, k-22/201, Azadpur village, North West Delhi-110033",
    contact: "8970202304",
    email: "smritasacred@gmail.com",
  },
];

export const CATEGORIES = ["All", "Sandalwood", "Floral", "Classic", "Herbal", "Resin", "Vedic", "Luxury"];

export const COMBO_PRICE = 250;
export const INDIVIDUAL_PRICE = 100;
export const COMBO_SIZE = 3;

export const calculateComboPrice = (items) => {
  const totalQuantity = items.reduce((sum, item) => sum + item.quantity, 0);
  const combos = Math.floor(totalQuantity / COMBO_SIZE);
  const remainder = totalQuantity % COMBO_SIZE;
  const comboTotal = combos * COMBO_PRICE;
  const remainderTotal = remainder * INDIVIDUAL_PRICE;
  const regularTotal = totalQuantity * INDIVIDUAL_PRICE;
  const actualTotal = comboTotal + remainderTotal;
  const savings = regularTotal - actualTotal;

  return {
    totalQuantity,
    combos,
    remainder,
    regularTotal,
    actualTotal,
    savings,
    hasCombo: combos > 0,
  };
};
